// Angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { extend, Internationalization } from '@syncfusion/ej2-base';
import {
  ScheduleComponent,
  EventSettingsModel,
  DayService,
  WeekService,
  WorkWeekService,
  MonthService,
  AgendaService,
  ResizeService,
  DragAndDropService,
  View,
  ViewsModel
} from '@syncfusion/ej2-angular-schedule';
import { scheduleData } from './data';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  providers: [
    DayService,
    WeekService,
    WorkWeekService,
    MonthService,
    AgendaService,
    ResizeService,
    DragAndDropService,
  ],
})
export class AppComponent {
  @ViewChild('schedule', { static: true })
  public scheduleObj: ScheduleComponent;
  public selectedDate: Date = new Date(2021, 0, 10);
  public eventSettings: EventSettingsModel = {
    dataSource: extend([], scheduleData, null, true) as Record<string, any>[],
  };
  public instance: Internationalization = new Internationalization();
  public dayInterval: number = 4;
  public weekInterval: number = 2;
  public weekTemp: boolean = true;
  public dayTemp: boolean = true;
  public temp: number = 1;

  getMajorTime(date: Date): string {
    return this.instance.formatDate(date, { skeleton: 'hm' });
  }
  getMinorTime(date: Date): string {
    return this.instance.formatDate(date, { skeleton: 'Hms' });
  }
  onZoomIn(): void {
    let currentView: View = this.scheduleObj.currentView;

    if (currentView == 'TimelineWeek') {
      if (this.weekTemp) {
        let currentDate: Date = this.calculateDate();
        this.scheduleObj.selectedDate = currentDate;
        (this.scheduleObj.views[1] as ViewsModel).interval = 1;
        this.scheduleObj.timeScale.slotCount = this.scheduleObj.timeScale.slotCount + 1;
        this.scheduleObj.refresh();
        this.weekTemp = false;
      } else {
        if (this.scheduleObj.timeScale.slotCount < 4) {
          let currentDate: Date = this.calculateDate();
          this.scheduleObj.selectedDate = currentDate;
          this.scheduleObj.timeScale.slotCount =
            this.scheduleObj.timeScale.slotCount + 2;
        } else {
          let currentDate: Date = this.calculateDate();
          this.scheduleObj.changeCurrentView('TimelineDay');
          this.scheduleObj.selectedDate = currentDate;
          this.scheduleObj.timeScale.interval = 60;
          this.scheduleObj.timeScale.slotCount = 1;
        }
      }
    } else if (currentView == 'TimelineDay') {
      if (this.dayTemp) {
        let currentDate: Date = this.calculateDate();
        this.scheduleObj.selectedDate = currentDate;
        (this.scheduleObj.views[0] as ViewsModel).interval = 1;
        this.scheduleObj.timeScale.slotCount =
          this.scheduleObj.timeScale.slotCount + 5;
        this.scheduleObj.refresh();
        this.dayTemp = false;
      } else {
        if (this.scheduleObj.timeScale.slotCount < 120) {
          let currentDate: Date = this.calculateDate();
          this.scheduleObj.selectedDate = currentDate;
          this.scheduleObj.timeScale.slotCount = 30 * this.temp;
          this.temp++;
          this.scheduleObj.refresh();
          this.scheduleObj.scrollTo("00:00", currentDate);
        }
      }
    } else {
      let currentDate: Date = this.calculateDate();
      this.scheduleObj.selectedDate = currentDate;
      this.scheduleObj.timeScale.slotCount = 1;
      this.scheduleObj.changeCurrentView('TimelineWeek');
      this.scheduleObj.refreshEvents();
    }
  }
  onZoomOut(): void {
    let currentView: View = this.scheduleObj.currentView;

    debugger
    if (currentView == 'TimelineWeek') {
      if (this.scheduleObj.timeScale.slotCount > 2) {
        let currentDate: Date = this.calculateDate();
        this.scheduleObj.selectedDate = currentDate;
        this.scheduleObj.scrollTo("00:00", currentDate);
        this.scheduleObj.timeScale.slotCount =
          this.scheduleObj.timeScale.slotCount - 2;
      } else {
        let currentDate: Date = this.calculateDate();
        this.scheduleObj.selectedDate = currentDate;
        this.scheduleObj.changeCurrentView('TimelineMonth');
        this.weekTemp = true;
      }
    } else if (currentView == 'TimelineDay') {
      if (this.scheduleObj.timeScale.slotCount > 30) {
        let currentDate: Date = this.calculateDate();
        this.scheduleObj.scrollTo("00:00", currentDate);
        this.scheduleObj.timeScale.slotCount =
          this.scheduleObj.timeScale.slotCount - 30;
      } else if (this.scheduleObj.timeScale.slotCount == 30) {
        let currentDate: Date = this.calculateDate();
        this.scheduleObj.scrollTo("00:00", currentDate);
        this.scheduleObj.timeScale.slotCount = 6;
      } else {
        let currentDate: Date = this.calculateDate();
        this.scheduleObj.changeCurrentView('TimelineWeek');
        this.scheduleObj.selectedDate = currentDate;
        this.scheduleObj.scrollTo("00:00", currentDate);
        this.scheduleObj.timeScale.interval = 60;
        this.scheduleObj.timeScale.slotCount = 4;
        this.dayTemp = true;
        this.temp = 1;
      }
    }
  }
  calculateDate() {
    var scrollLeft = this.scheduleObj.element.querySelector(".e-content-wrap").scrollLeft;
    var headerCellIndex = scrollLeft / (this.scheduleObj.element.querySelectorAll(".e-header-cells")[0] as HTMLElement).offsetWidth;
    var currentHeaderCell = this.scheduleObj.element.querySelectorAll(".e-header-cells")[Math.floor(headerCellIndex)];
    var currentViewDate = currentHeaderCell.getAttribute("data-date");
    return new Date(parseInt(currentViewDate));
  }
}

<div class="control-section">
  <div class="col-lg-9 content-wrapper">
  <div>
  <button ejs-button (click)="onZoomIn()">Zoom In(-)</button>
  <button ejs-button (click)="onZoomOut()">Zoom Out(+)</button>
</div>
<br />
    <ejs-schedule #schedule width='100%' height='550px' [(selectedDate)]="selectedDate" [eventSettings]="eventSettings" currentView="TimelineMonth"
    cssClass='schedule-cell-dimension'>
    <e-views>
      <e-view option="TimelineDay" [interval]="dayInterval"></e-view>
      <e-view option="TimelineWeek" [interval]="weekInterval"></e-view>
     <e-view option="TimelineMonth"></e-view>
  </e-views>
  <e-header-rows>
  <e-header-row option='Month'></e-header-row>
  <e-header-row option='Date'></e-header-row>
  <e-header-row option='Hour'></e-header-row>
  
</e-header-rows>
<ng-template #timeScaleMajorSlotTemplate let-data> 
<div class="majorTime">{{getMajorTime(data.date)}}</div> 
</ng-template> 
<ng-template #timeScaleMinorSlotTemplate let-data> 
<div class="minorTime">{{getMinorTime(data.date)}}</div> 
</ng-template> 
    </ejs-schedule>
  </div>
</div>

// Vue/src/App.vue
<template>
    <div id='app'>
      <ejs-button v-on:click='zoomin'>Zoom In</ejs-button>
      <ejs-button v-on:click='zoomout'>Zoom Out</ejs-button>
        <ejs-schedule id="zoom" ref='scheduleObj' height='550px' width='100%' :selectedDate='selectedDate' :cssClass='cssClass' :currentView='currentView' :views='views' :eventSettings='eventSettings'
        :headerRows="headerRows" :timeScale="timeScale">
        </ejs-schedule>
    </div>
</template>
<script>
import { ScheduleComponent, TimelineViews, TimelineMonth } from "@syncfusion/ej2-vue-schedule";
import { ButtonComponent } from "@syncfusion/ej2-vue-buttons";
import { scheduleData } from './datasource.js';
import { Internationalization } from '@syncfusion/ej2-base';
import { createApp } from "vue";

const app = createApp();


import '../node_modules/@syncfusion/ej2-base/styles/material.css';
import '../node_modules/@syncfusion/ej2-buttons/styles/material.css';
import '../node_modules/@syncfusion/ej2-calendars/styles/material.css';
import '../node_modules/@syncfusion/ej2-dropdowns/styles/material.css';
import '../node_modules/@syncfusion/ej2-inputs/styles/material.css';
import '../node_modules/@syncfusion/ej2-navigations/styles/material.css';
import '../node_modules/@syncfusion/ej2-popups/styles/material.css';
import '../node_modules/@syncfusion/ej2-vue-schedule/styles/material.css';
// const app = createApp();

   var instance = new Internationalization();
  var majorTemplateVue = app.component('majorSlotTemplate', {
    template: '<div>{{majorSlotTemplate(data.date)}}</div>',
    data: () => ({}),
    methods: {
        majorSlotTemplate: function (date) {
            return instance.formatDate(date, { skeleton: 'hm' });
        }
    }
});
   var minorTemplateVue =  app.component('minorSlotTemplate', {
     template: '<div>{{minorSlotTemplate(data.date)}}</div>',
    data: () => ({}),
    methods: {
        minorSlotTemplate: function (date) {
            return instance.formatDate(date, { skeleton: 'Hms' });
        }
    }
});
var weekTemp = true;
var dayTemp = true;
var temp = 1;

export default {
    name: "App",
    // Declaring component and its directives
    components: {
        'ejs-schedule': ScheduleComponent,
        'ejs-button': ButtonComponent
    },
    // Bound properties declaration
    data() {
        return {
            selectedDate: new Date(2021, 0, 10),
           currentView: 'TimelineMonth',
            views: [
              { option: 'TimelineDay', interval: 4 },
              { option: 'TimelineWeek', interval: 3 },
              { option: 'TimelineMonth'}
            ],
            cssClass: 'schedule-cell-dimension',
        headerRows: [
          { option: 'Month' },
          { option: 'Date' },
          { option: 'Hour' }
        ],
            eventSettings: {
                dataSource: scheduleData
            },
            timeScale: {
                enable: true,
                 majorSlotTemplate: function () {
                    return { template: majorTemplateVue };
                },
                minorSlotTemplate: function () {
                    return { template: minorTemplateVue };
                },
            },
        };
    },
    methods : {
        zoomin: function() {
          var scheduleObj = document.getElementById('zoom').ej2_instances[0];
            var currentView = scheduleObj.currentView;
      var currentDate = this.calculateDate();
      if (currentView === 'TimelineWeek') {
          if (weekTemp) {
              scheduleObj.selectedDate = currentDate;
              scheduleObj.views[1].interval = 1;
              scheduleObj.timeScale.slotCount = scheduleObj.timeScale.slotCount + 1;
              scheduleObj.refresh();
              weekTemp = false;
          }
          else {
              if (scheduleObj.timeScale.slotCount < 4) {
                  scheduleObj.selectedDate = currentDate;
                  scheduleObj.timeScale.slotCount = scheduleObj.timeScale.slotCount + 2;
              }
              else {
                  scheduleObj.changeCurrentView('TimelineDay');
                  scheduleObj.selectedDate = currentDate;
                  scheduleObj.timeScale.interval = 60;
                  scheduleObj.timeScale.slotCount = 1;
              }
          }
      }
      else if (currentView === 'TimelineDay') {
          if (dayTemp) {
              scheduleObj.selectedDate = currentDate;
              scheduleObj.views[0].interval = 1;
              scheduleObj.timeScale.slotCount =
                  scheduleObj.timeScale.slotCount + 5;
              scheduleObj.refresh();
              dayTemp = false;
          }
          else {
              if (scheduleObj.timeScale.slotCount < 120) {
                  scheduleObj.selectedDate = currentDate;
                  scheduleObj.timeScale.slotCount = 30 * temp;
                  temp++;
                  scheduleObj.refresh();
                  scheduleObj.scrollTo("00:00", currentDate);
              }
          }
      }
      else {
          scheduleObj.selectedDate = currentDate;
          scheduleObj.timeScale.slotCount = 1;
          scheduleObj.changeCurrentView('TimelineWeek');
          scheduleObj.refreshEvents();
      }
        },
        zoomout: function() {
          var scheduleObj = document.getElementById('zoom').ej2_instances[0];
            var currentView = scheduleObj.currentView;
      var currentDate = this.calculateDate();
      if (currentView === 'TimelineWeek') {
          if (scheduleObj.timeScale.slotCount > 2) {
              scheduleObj.selectedDate = currentDate;
              scheduleObj.scrollTo("00:00", currentDate);
              scheduleObj.timeScale.slotCount =
                  scheduleObj.timeScale.slotCount - 2;
          }
          else {
              scheduleObj.selectedDate = currentDate;
              scheduleObj.changeCurrentView('TimelineMonth');
              weekTemp = true;
          }
      }
      else if (currentView === 'TimelineDay') {
          if (scheduleObj.timeScale.slotCount > 30) {
              scheduleObj.scrollTo("00:00", currentDate);
              scheduleObj.timeScale.slotCount =
                  scheduleObj.timeScale.slotCount - 30;
          }
          else if (scheduleObj.timeScale.slotCount === 30) {
              scheduleObj.scrollTo("00:00", currentDate);
              scheduleObj.timeScale.slotCount = 6;
          }
          else {
              scheduleObj.changeCurrentView('TimelineWeek');
              scheduleObj.selectedDate = currentDate;
              scheduleObj.scrollTo("00:00", currentDate);
              scheduleObj.timeScale.interval = 60;
              scheduleObj.timeScale.slotCount = 4;
              this.dayTemp = true;
              temp = 1;
          }
      }
        },
        calculateDate: function() {
          var scheduleObj = document.getElementById('zoom').ej2_instances[0];
            var scrollLeft = scheduleObj.element.querySelector(".e-content-wrap").scrollLeft;
      var headerCellIndex = scrollLeft / scheduleObj.element.querySelectorAll(".e-header-cells")[0].offsetWidth;
      var currentHeaderCell = scheduleObj.element.querySelectorAll(".e-header-cells")[Math.floor(headerCellIndex)];
      var currentViewDate = currentHeaderCell.getAttribute("data-date");
      return new Date(parseInt(currentViewDate));
        }
    },
      provide: {
      schedule: [TimelineViews, TimelineMonth]
    }
};
</script>

<style>
        .schedule-cell-dimension.e-schedule .e-timeline-month-view .e-content-wrap table col,
        .schedule-cell-dimension.e-schedule .e-timeline-view .e-content-wrap table col {
            width: 100px;
        }

        .schedule-cell-dimension.e-schedule .e-timeline-view .e-work-cells,
        .schedule-cell-dimension.e-schedule .e-timeline-month-view .e-work-cells {
            height: 600px;
        }
    </style>
